### ISSUE TITLE
Uniqueness not guaranteed if the same ref is used in multiple data files

### ISSUE THREAD

**Issue by dmartinol** [app-sre/qontract-validator#54]
Consider the following customer-schema:
```
"$schema": /metaschema-1.json
version: '1.0'
type: object

additionalProperties: false
properties:
...
  admin-user:
    "$ref": "/common-1.json#/definitions/crossref"
    "$schemaRef": "/admin-user-schema.yaml"
...
```
And the related admin-user-schema:
```
"$schema": /metaschema-1.json
version: '1.0'
type: object

additionalProperties: false
properties:
...
  email:
    type: string
    format: email
  username:
    type: string
...
```

Then in graphql schema define uniqueness of the `email` field:
```
- name: "AdminUser_v1"
  fields:
...
    - { name: email, type: string, isRequired: true, isUnique: true }
...
```

The uniqueness is not guaranteed if two documents with customer-schema are sharing the same admin-user configuration, as in:
```
$schema: "/customer-schema.yaml"
...
admin-user:
  "$ref": "/admin-user-1.yaml"
...
```
The uniqueness is only guaranteed if they all have their own admin-user document
